name: Deploy Posts Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests
         

      - name: Build Docker image
        run: docker build --no-cache -t posts-service .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name postsregistryvv96c9

      - name: Push image to ACR
        run: |
          docker tag posts-service postsregistryvv96c9.azurecr.io/posts-service:latest
          docker push postsregistryvv96c9.azurecr.io/posts-service:latest

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
          --resource-group terraform-demo-rg \
          --name posts-aks-cluster \
          --overwrite-existing

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/posts-service \
          posts-service=postsregistryvv96c9.azurecr.io/posts-service:latest

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/posts-service
