name: Deploy Posts Service

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests


      - name: Build Docker image
        run: |
          docker build --no-cache \
          -t posts-service:${{ github.sha }} .


      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin


      - name: Push image to GHCR
        run: |
          docker tag posts-service:${{ github.sha }} \
          ghcr.io/saqibmehmood123/posts-service:${{ github.sha }}

          docker push \
          ghcr.io/saqibmehmood123/posts-service:${{ github.sha }}


      - name: Deploy with Helm
        run: |
          helm upgrade --install posts-release \
          ./post-service-chart \
          -n blog-app \
          --set image.tag=${{ github.sha }}


      - name: Verify deployment
        run: |
          kubectl rollout status \
          deployment/posts-release-post-service-chart \
          -n blog-app
